services:
  cassandra:
    image: cassandra:4.1
    container_name: cassandra
    restart: unless-stopped
    ports:
      - "9042:9042"
    environment:
      CASSANDRA_CLUSTER_NAME: "url_shortener_cluster"
      CASSANDRA_NUM_TOKENS: 256
      CASSANDRA_START_RPC: "true"

  redis:
    image: redis:8.4-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node_app
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
    depends_on:
      - redis
      - cassandra
    command: npm run dev
